import { test } from 'node:test';
import assert from 'node:assert/strict';
import { validateCredentials, assertNoCredentials, safeFailure, summarize, ApiError } from '../src/pronote/contracts';
import { dateFromLabel, parseTimetable, parseGrades, parseAssignments, parseResources } from '../src/pronote/parsers';
import { seal, unseal, randomToken, equalSecret } from '../worker/crypto';
import { isConsoleOriginAllowed } from '../src/pronote/http';
const input={username:'test-user',password:'not-a-real-password'};
test('console origin works behind HTTPS proxy without accepting other sites',()=>{
  assert.equal(isConsoleOriginAllowed(new Request('http://localhost:3000/api/pronote',{headers:{origin:'https://console.example.test',host:'localhost:3000','x-forwarded-host':'console.example.test'}})),true);
  assert.equal(isConsoleOriginAllowed(new Request('http://localhost:3000/api/pronote',{headers:{origin:'http://127.0.0.1:3000',host:'127.0.0.1:3000'}})),true);
  assert.equal(isConsoleOriginAllowed(new Request('http://localhost:3000/api/pronote',{headers:{origin:'https://evil.example.test','x-forwarded-host':'console.example.test'}})),false);
  assert.equal(isConsoleOriginAllowed(new Request('http://localhost:3000/api/pronote',{headers:{origin:'null'}})),false);
});
test('validates ENT77 request and selects default modules',()=>{assert.equal(validateCredentials(input).modules.length,8);});
test('rejects missing and malformed credentials',()=>{for(const value of [null,[],{},1,{...input,password:''},{...input,username:'x'.repeat(201)}])assert.throws(()=>validateCredentials(value));});
test('rejects SSRF targets and session-bearing URLs',()=>{for(const pronoteUrl of ['http://school.index-education.net/pronote/eleve.html','https://127.0.0.1/pronote/eleve.html','https://school.index-education.net.evil.test/pronote/eleve.html','https://school.index-education.net/pronote/eleve.html?ticket=private','https://a:b@school.index-education.net/pronote/eleve.html','https://school.index-education.net:8443/pronote/eleve.html'])assert.throws(()=>validateCredentials({...input,pronoteUrl}));});
test('does not silently accept unsupported ENT or modules',()=>{assert.throws(()=>validateCredentials({...input,entUrl:'https://evil.test'}));assert.throws(()=>validateCredentials({...input,modules:['unknown']}));assert.throws(()=>validateCredentials({...input,modules:[]}));});
test('accepts EduConnect for student and parent accounts',()=>{
  assert.equal(validateCredentials({...input,provider:'educonnect'}).provider,'educonnect');
  assert.equal(validateCredentials({...input,provider:'educonnect',account:'parent'}).account,'parent');
  assert.equal(validateCredentials({...input,entUrl:'https://educonnect.education.gouv.fr/'}).provider,'educonnect');
  assert.throws(()=>validateCredentials({...input,provider:'google'}));
  assert.throws(()=>validateCredentials({...input,account:'teacher'}));
});
test('deduplicates valid modules',()=>{assert.deepEqual(validateCredentials({...input,modules:['notes','notes']}).modules,['notes']);});
test('date parsing handles accents and year transitions without local timezone shift',()=>{const ref=new Date('2026-09-17T12:00:00Z');assert.equal(dateFromLabel('Cours du 14 septembre de 8 heures 30',ref),'2026-09-14');assert.equal(dateFromLabel('Pour le 3 février 2027',ref),'2027-02-03');assert.equal(dateFromLabel('31/02/2026',ref),null);});
test('timetable reads accessible date and time without pixel inference',()=>{const a=parseTimetable('<div class="cours-simple" aria-label="Cours du 14 septembre 2026 de 8 heures 30 à 10 heures 20"><div class="content_cours"><div role="listitem">MATHEMATIQUES</div><div role="listitem">204</div></div></div>');assert.equal(a.length,1);assert.equal(a[0].heureDebut,'08:30');assert.equal(a[0].heureFin,'10:20');assert.equal(a[0].salle,'204');assert.equal(a[0].professeur,null);});
test('grades preserve unknown coefficients and real scale',()=>{const a=parseGrades('<div class="liste_contenu_cellule_contenu"><time>14/09/2026</time><div class="titre-principal">Maths</div><span class="note-devoir">7,5 / 10</span></div>');assert.equal(a.evaluations[0].valeur,7.5);assert.equal(a.evaluations[0].sur,10);assert.equal(a.evaluations[0].coefficient,null);});
test('homework preserves text and checked state',()=>{const a=parseAssignments('<h2>Pour le 18 septembre 2026</h2><div class="conteneur-item"><h3 class="titre-matiere est-fait">Français</h3><div class="description">Le parfait et l’imparfait.</div></div>','https://school.index-education.net/pronote/');assert.equal(a.length,1);assert.equal(a[0].fait,true);assert.equal(a[0].pourLe,'2026-09-18');assert.match(a[0].description,/imparfait/);});
test('resources without attachments are retained',()=>{assert.equal(parseResources('<div class="conteneur-item"><h3 class="titre-matiere">Histoire</h3><div class="description">Séance sans document</div></div>','https://school.index-education.net/').length,1);});
test('empty HTML does not fabricate school data',()=>{assert.deepEqual(parseTimetable(''),[]);assert.deepEqual(parseGrades('').evaluations,[]);assert.deepEqual(parseAssignments('','https://example.test'),[]);});
test('credential keys rejected recursively',()=>{for(const key of ['password','USERNAME','ent_pass','token','cookie'])assert.throws(()=>assertNoCredentials({data:[{[key]:'private'}]}));});
test('unknown technical errors do not leak their message',()=>{const r=safeFailure(new Error('private password and cookie'));assert.ok(!JSON.stringify(r).includes('private password'));assert.equal(r.error?.code,'INTERNAL_ERROR');});
test('public summary excludes contents and credentials',()=>{const r=safeFailure(new ApiError('ENT_AUTH_FAILED',401,'ent','Connexion refusée'));const s=summarize(r);assert.ok(!('data' in s));assert.ok(!('error' in s));});
test('AES-GCM round trip and wrong-key rejection',async()=>{const key=randomToken();const packed=await seal({secret:'example'},key);assert.ok(!packed.includes('example'));assert.deepEqual(await unseal(packed,key),{secret:'example'});await assert.rejects(()=>unseal(packed,randomToken()));});
test('runner token comparisons use complete values',async()=>{assert.equal(await equalSecret('same','same'),true);assert.equal(await equalSecret('same','different'),false);});
