'use client';
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, Check, ChevronRight, CircleHelp, Code2, Copy, Database, ExternalLink, FileJson, GitBranch, Layers, Loader2, LockKeyhole, Play, RefreshCw, Server, ShieldCheck, Terminal, X } from 'lucide-react';
import { MODULES, type ModuleName, type ModuleReport } from '@/pronote/contracts';
const BASE='https://pronote-api.hugdu77777.workers.dev';
const labels:Record<ModuleName,string>={emploiDuTemps:'Emploi du temps',notes:'Notes',agenda:'Travail à faire',ressources:'Ressources',vieScolaire:'Vie scolaire',competences:'Compétences',actualites:'Actualités',cantine:'Cantine'};
interface CheckRecord{id:number;version:string;mode:string;success:boolean;durationMs:number;modules:ModuleReport[];createdAt:string;errorCode:string|null}
interface Monitor{remote:{version?:string;runnerOnline?:boolean;queueDepth?:number;running?:number;lastExtraction?:{success:boolean;durationMs:number;modules:ModuleReport[];timestamp:string}}|null;checks:CheckRecord[];checkedAt:string}
type Reply={success?:boolean;status?:string;jobId?:string;jobToken?:string;error?:{code?:string;message?:string};[key:string]:unknown};
export default function Page(){
 const [monitor,setMonitor]=useState<Monitor|null>(null);const [refreshing,setRefreshing]=useState(false);const [copied,setCopied]=useState(false);
 const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [apiKey,setApiKey]=useState('');const [modules,setModules]=useState<ModuleName[]>(['emploiDuTemps','notes','agenda','ressources']);
 const [login,setLogin]=useState<'ent77'|'educonnect_student'|'educonnect_parent'>('ent77');
 const provider=login==='ent77'?'ent77':'educonnect';const account=login==='educonnect_parent'?'parent':'student';
 const [result,setResult]=useState<Reply|null>(null);const [phase,setPhase]=useState('');const [busy,setBusy]=useState(false);const [elapsed,setElapsed]=useState(0);const [tab,setTab]=useState<'response'|'request'>('response');
 const [notice,setNotice]=useState('');const controller=useRef<AbortController|null>(null);const job=useRef<{id:string;token:string}|null>(null);
 const refresh=useCallback(async()=>{setRefreshing(true);try{const r=await fetch('/api/monitor',{cache:'no-store'});if(!r.ok)throw new Error();setMonitor(await r.json());}catch{setNotice('Impossible de rafraîchir l’état pour le moment.');}finally{setRefreshing(false);}},[]);
 useEffect(()=>{void refresh();const t=setInterval(()=>void refresh(),30000);return()=>{clearInterval(t);controller.current?.abort();};},[refresh]);
 useEffect(()=>{if(!busy)return;const t=setInterval(()=>setElapsed(x=>x+1),1000);return()=>clearInterval(t);},[busy]);
 const latest=monitor?.checks[0];const reports=latest?.modules||monitor?.remote?.lastExtraction?.modules||[];
 const verified=latest?.success??monitor?.remote?.lastExtraction?.success;const online=monitor?.remote?.version==='5.0.0'&&monitor.remote.runnerOnline;
 async function copy(){try{await navigator.clipboard.writeText(`${BASE}/api/v1/scrape-pronote`);setCopied(true);setTimeout(()=>setCopied(false),1800);}catch{setNotice('La copie n’est pas disponible dans ce navigateur.');}}
 async function execute(e:FormEvent){
  e.preventDefault();if(!modules.length){setNotice('Sélectionnez au moins une rubrique.');return;}
  setBusy(true);setElapsed(0);setResult(null);setTab('response');setPhase('Connexion à la passerelle…');setNotice('');job.current=null;
  const ctrl=new AbortController();controller.current=ctrl;
  const h:Record<string,string>={'Content-Type':'application/json'};if(apiKey)h['X-API-Key']=apiKey;
  const timer=setTimeout(()=>ctrl.abort(),240000);
  try{
   const request=fetch('/api/pronote',{method:'POST',headers:h,body:JSON.stringify({username,password,modules,provider,account}),signal:ctrl.signal});setPassword('');
   let response=await request;let payload:Reply=await response.json();
   if(payload.jobId&&payload.jobToken)job.current={id:payload.jobId,token:payload.jobToken};
   while(response.status===202&&job.current){
    setPhase(payload.status==='queued'?'Demande en file · démarrage du moteur si nécessaire…':'Session isolée · lecture des rubriques Pronote…');
    await new Promise<void>((resolve,reject)=>{const timer=setTimeout(resolve,3000);ctrl.signal.addEventListener('abort',()=>{clearTimeout(timer);reject(new DOMException('Stopped','AbortError'));},{once:true});});
    response=await fetch(`/api/pronote/jobs/${job.current.id}`,{headers:{...h,'X-Job-Token':job.current.token},signal:ctrl.signal,cache:'no-store'});payload=await response.json();
   }
   const {jobToken,...safe}=payload;void jobToken;setResult(safe);setPhase(payload.success?(payload.status==='partial'?'Extraction terminée · consultez les limites par rubrique.':'Extraction terminée.'):(payload.error?.message||'Le serveur a retourné une erreur.'));
   void refresh();
  }catch(error){setPhase(error instanceof DOMException&&error.name==='AbortError'?'Suivi arrêté. Le résultat serveur expire automatiquement.':'La passerelle n’a pas répondu. Réessayez après vérification du moteur.');}
  finally{clearTimeout(timer);setBusy(false);controller.current=null;}
 }
 async function erase(){if(!job.current){setResult(null);return;}try{const h:Record<string,string>={'X-Job-Token':job.current.token};if(apiKey)h['X-API-Key']=apiKey;const r=await fetch(`/api/pronote/jobs/${job.current.id}`,{method:'DELETE',headers:h});if(!r.ok)throw new Error();setResult(null);job.current=null;setPhase('Résultat supprimé du serveur et de cette console.');}catch{setNotice('Suppression non confirmée. Le résultat expire après cinq minutes.');}}
 function download(){if(!result)return;const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='pronote-resultat.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="app-shell">
  <aside className="sidebar"><a className="brand" href="#top"><span className="brand-mark"><Code2 size={22}/></span><span>pronote<span className="brand-api"> / api</span></span></a><div className="workspace"><span className="workspace-icon">J</span><div><strong>JeanHug</strong><small>Espace développeur</small></div><span className="version-chip">v5</span></div><p className="nav-label">ESPACE DE TRAVAIL</p><nav><a href="#top" className="nav-current"><Layers size={17}/> Vue d’ensemble</a><a href="#console"><Terminal size={17}/> Console API <span className="nav-shortcut">↵</span></a><a href="#verification"><ShieldCheck size={17}/> Vérifications</a><a href={`${BASE}/docs`} target="_blank" rel="noreferrer"><FileJson size={17}/> Documentation <ArrowUpRight size={14}/></a></nav><div className="sidebar-bottom"><div className="safety-note"><LockKeyhole size={18}/><strong>Privé par conception</strong><p>Les identifiants restent côté serveur. Aucune donnée scolaire dans les journaux de test.</p></div><a className="repo-link" href="https://github.com/JeanHug/Pronote-API" target="_blank" rel="noreferrer"><GitBranch size={17}/> Voir le dépôt <ArrowUpRight size={14}/></a><small className="sidebar-footer">API non officielle · ENT77</small></div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={13}/><span>Pronote API</span></div><div className="topbar-right"><span className="production-pill"><span/> Production</span><a href={`${BASE}/docs`} target="_blank" rel="noreferrer" aria-label="Ouvrir la documentation"><CircleHelp size={18}/></a><span className="avatar">JH</span></div></header>
   <main className="content" id="top"><div className="intro"><div><div className="eyebrow"><span/> UNE NOUVELLE BASE, VÉRIFIABLE.</div><h1>Votre API, au clair.</h1><p>Une connexion réelle. Des réponses structurées.<br className="mobile-break"/> Et un état explicite pour chaque rubrique.</p></div><button className="button secondary" onClick={()=>void refresh()} disabled={refreshing}><RefreshCw size={15} className={refreshing?'spin':''}/> Actualiser l’état</button></div>
   {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Fermer"><X size={15}/></button></div>}
   <div className="metrics"><section className="metric"><div className="metric-title"><Server size={17}/> Moteur d’extraction <span className={`dot ${online?'green':''}`}/></div><strong>{!monitor?'Vérification…':online?'En ligne':'En attente'}</strong><p>{online?'GitHub Actions · session isolée':'Un appel peut déclencher son démarrage'}</p></section><section className="metric"><div className="metric-title"><ShieldCheck size={17}/> Dernière vérification</div><strong>{verified===undefined?'À vérifier':verified?'Extraction validée':'À examiner'}{verified&&<Check size={17}/>}</strong><p>{latest?`${latest.mode} · ${new Date(latest.createdAt).toLocaleString('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}`:monitor?.remote?.lastExtraction?'Dernier résultat du moteur':'Aucun test enregistré pour le moment'}</p></section><section className="metric"><div className="metric-title"><Activity size={17}/> File d’attente</div><strong>{monitor?.remote?.queueDepth??'—'} <span className="metric-unit">demande(s)</span></strong><p>{monitor?.remote?.running??0} traitement en cours · capacité limitée</p></section></div>
   <section className="endpoint-bar"><span className="method">POST</span><code>{BASE}<b>/api/v1/scrape-pronote</b></code><button onClick={copy} aria-label="Copier l’endpoint">{copied?<Check size={16}/>:<Copy size={16}/>}</button></section>
   <section className="console-section" id="console"><div className="section-heading"><div><h2><Terminal size={19}/> Console API</h2><p>Testez une extraction avec un compte que vous êtes autorisé à consulter.</p></div><span className="small-chip">JSON · REST</span></div><div className="console-grid"><form className="request-panel" onSubmit={execute}><div className="panel-heading"><span>Configurer la requête</span><span className="step-label">01</span></div><label>Identifiant ENT <input required value={username} onChange={e=>setUsername(e.target.value)} placeholder="Votre identifiant" autoComplete="username" maxLength={200} disabled={busy}/></label><label>Mot de passe <div className="password-wrap"><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Votre mot de passe ENT" autoComplete="current-password" maxLength={200} disabled={busy}/><LockKeyhole size={15}/></div></label><p className="field-help"><ShieldCheck size={13}/> Jamais sauvegardé dans cette console.</p><label>Mode de connexion<select className="mode-select" value={login} onChange={e=>setLogin(e.target.value as 'ent77'|'educonnect_student'|'educonnect_parent')} disabled={busy}><option value="ent77">Compte local ENT77 (personnel &amp; invité)</option><option value="educonnect_student">Élève (EduConnect)</option><option value="educonnect_parent">Responsable / Parent (EduConnect)</option></select></label><div className="form-divider"/><div className="field-label">Rubriques à extraire <span>{modules.length} sélectionnées</span></div><div className="module-options">{MODULES.map(m=><label className="checkbox-label" key={m}><input type="checkbox" checked={modules.includes(m)} disabled={busy} onChange={()=>setModules(v=>v.includes(m)?v.filter(x=>x!==m):[...v,m])}/>{labels[m]}</label>)}</div><details className="advanced"><summary>Options d’accès</summary><label>Clé d’API, si configurée<input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="off" placeholder="Optionnel"/></label><p>Connecteur ENT77 · espace élève de l’établissement configuré.</p></details><button className="button primary execute" disabled={busy||!modules.length} type="submit">{busy?<><Loader2 size={16} className="spin"/> Extraction en cours <span>{elapsed}s</span></>:<><Play size={15} fill="currentColor"/> Exécuter la requête <ArrowRight size={16}/></>}</button>{busy&&<button className="stop-button" type="button" onClick={()=>controller.current?.abort()}>Arrêter le suivi</button>}</form>
   <div className="response-panel"><div className="response-tabs"><div><button className={tab==='response'?'selected':''} onClick={()=>setTab('response')}>Réponse</button><button className={tab==='request'?'selected':''} onClick={()=>setTab('request')}>Requête</button></div><span className="json-badge">JSON</span></div>{tab==='request'?<pre>{JSON.stringify({username:'VOTRE_IDENTIFIANT',password:'••••••••',provider,account,modules},null,2)}</pre>:result?<><div className="response-status"><span className={`dot ${result.success?'green':'red'}`}/>{result.success?'Réponse reçue':'Erreur explicite'}<span>{String(result.status||result.error?.code||'')}</span><button onClick={download} aria-label="Télécharger le résultat"><ArrowDownToLine size={15}/></button></div><pre>{JSON.stringify(result,null,2)}</pre><button className="erase-button" onClick={()=>void erase()}>Effacer le résultat</button></>:<div className="response-empty"><div className={`response-symbol ${busy?'pulsing':''}`}>{busy?<Loader2 size={28} className="spin"/>:<Code2 size={28}/>}</div><h3>{busy?'Le moteur fait son travail.':'Votre réponse apparaîtra ici.'}</h3><p>{busy?phase:'Configurez les rubriques, puis lancez votre première requête. Les réponses 202 sont suivies automatiquement.'}</p><div className="response-flow"><span>ENT</span><ChevronRight size={13}/><span>PRONOTE</span><ChevronRight size={13}/><span>JSON</span></div></div>}<div className="response-footer"><LockKeyhole size={13}/><span>{phase&&!busy?phase:'Les résultats contiennent des données privées. Ne les partagez pas.'}</span></div></div></div></section>
   <section id="verification" className="verification"><div className="section-heading"><div><h2><ShieldCheck size={19}/> Vérification des rubriques</h2><p>Compteurs du dernier test, sans noms, notes individuelles ni identifiants.</p></div><span className="small-chip">{reports.length?`${reports.length} rubriques vérifiées`:'En attente de résultat'}</span></div><div className="verification-list">{MODULES.map(m=>{const report=reports.find(x=>x.module===m);return <div className="verification-row" key={m}><span className={`module-icon ${report?.status==='ok'?'module-ok':''}`}><FileJson size={16}/></span><strong>{labels[m]}</strong><span className="scope">{report?.scope||'Pas encore testée'}</span><span className="row-count">{report?report.count:'—'}</span><span className={`state-label ${report?.status||''}`}>{!report?'À vérifier':report.status==='ok'?'Extrait':report.status==='empty'?'Vide confirmé':report.status==='unavailable'?'Non disponible':'À examiner'}</span></div>;})}</div><p className="honest-note"><CircleHelp size={14}/> Un statut « non disponible » signifie que la rubrique n’est pas exposée par le compte. Aucun contenu n’est inventé.</p></section>
   <div className="bottom-cards"><section><span className="card-icon"><Database size={19}/></span><h3>Une rétention courte, et explicite.</h3><p>Identifiants chiffrés puis effacés à la prise en charge. Résultats chiffrés, protégés par un jeton de lecture et conservés cinq minutes.</p></section><section><span className="card-icon"><FileJson size={19}/></span><h3>Un contrat que vous pouvez lire.</h3><p>Portée, erreurs, rubriques et suivi asynchrone sont documentés. Les champs non exposés valent null, pas une valeur supposée.</p><a href={`${BASE}/docs`} target="_blank" rel="noreferrer">Ouvrir la documentation <ExternalLink size={13}/></a></section></div><footer className="page-footer"><span>Pronote API v5 · Non affiliée à Index Éducation</span><span><span className="dot green"/> Sans publication sur les issues GitHub</span></footer></main>
  </div>
 </div>;
}
